alias oubuild='(cd ~/dev/bfs/ou/ou-config/BritishFriendly; ant -f Build.xml -Dou.home=/home/daniel.barrington/dev/bfs/ou/system)'
alias oupageflow='(cd ~/dev/bfs/ou/ou-config/BritishFriendly/Base && ant -f Build.xml -Dou.home=/home/daniel.barrington/dev/bfs/ou/system)'
alias ouworkflow='(cd ~/dev/bfs/ou/ou-config/BritishFriendly; ant -f Build.xml -Dou.home=/home/daniel.barrington/dev/bfs/ou/system -Dworkflows.force-unload=true)'
alias oudeploy='(cd ~/dev/bfs/ou/ou-config/BritishFriendly; ant -f Build.xml -Dou.home=/home/daniel.barrington/dev/bfs/ou/system -Dwebdav.host=52.210.69.137 -Dwebdav.port=80)'
alias oustart='cd ~/dev/bfs/ou/system; ant -f Build.xml -DDdbusername=root -Ddbpassword=Pa55w0rd -DJBOSS_OPTS="-b 172.31.90.48" start'
alias oustop='ant -f Build.xml stop'
alias ousetup='cd ~/dev/bfs/ou/system; ant -f Build.xml -Ddbusername=root -Ddbpassword=Pa55w0rd -Ddbhost=127.0.0.1 -DJBOSS_OPTS="-b 172.31.90.48" stop teardown setup start'
alias outeardown='cd ~/dev/bfs/ou/system; ant -f Build.xml -Ddbusername=root -Ddbpassword=Pa55w0rd -Ddbhost=127.0.0.1 teardown'
