alias oubuild='(cd /home/daniel.barrington/dev/bfs/ou/ou-config/BritishFriendly; ant -f Build.xml -Dou.home=/home/daniel.barrington/dev/bfs/ou/system)'
alias oupageflow='(cd /home/daniel.barrington/dev/bfs/ou/ou-config/BritishFriendly/Base && ant -f Build.xml -Dou.home=/home/daniel.barrington/dev/bfs/ou/system)'
alias ouworkflow='(cd /home/daniel.barrington/dev/bfs/ou/ou-config/BritishFriendly; ant -f Build.xml -Dou.home=/home/daniel.barrington/dev/bfs/ou/system -Dworkflows.force-unload=true)'
alias oudeploy='(cd /home/daniel.barrington/dev/bfs/ou/ou-config/BritishFriendly; ant -f Build.xml -Dou.home=/home/daniel.barrington/dev/bfs/ou/system -Dwebdav.host=52.210.69.137 -Dwebdav.port=80)'
alias oustart='cd /home/daniel.barrington/dev/bfs/ou/system; ant -f Build.xml -Dmysql.root.password=Pa55w0rd start'
alias oustop='ant -f Build.xml -Dmysql.root.password=Pa55w0rd stop'
alias ousetup='cd /home/daniel.barrington/dev/bfs/ou/system; ant -f Build.xml -Dmysql.root.password=Pa55w0rd -Dmysql.root.username=root -Dmysql.root.host=127.0.0.1 stop teardown setup start'
alias outeardown='cd /home/daniel.barrington/dev/bfs/ou/system; ant -f Build.xml -Dmysql.root.password=Pa55w0rd teardown'
alias ou='"cd $(pwd)/deploy/ou && /bin/zsh ou.sh"'
